### ISSUE TITLE
Allow other extractors to bridge from this extractor

### ISSUE THREAD

**Issue by twlite** [retrouser955/discord-player-youtubei#14]
this extractor needs to implement `bridge` method to accept bridge requests sent by another extractor. This method receives the track object that requires bridging and the extractor that requested the bridge, just as a precaution to limit whom to accept/deny.

Pseudocode:
```ts
public async bridge(track, ext) {
    const query = ext?.createBridgeQuery(track) ?? track.title;
    const alt = await this.handle(query)
    return this.stream(alt.tracks[0])
}
```

**Comment by retrouser955** [comment]
Planned for 1.2.x

**Comment by retrouser955** [comment]
Closed via [this commit](https://github.com/retrouser955/discord-player-youtubei/commit/7b5fb94d90f3d163d551049ee6fb6ee2ad7301a6)
