### ISSUE TITLE
PlayerError: Failed to extract n-token decipher algorithm (i sawthe other issue but i think that my code ismalfunctioning in a different way)

### ISSUE THREAD

**Issue by MatyxCZ** [retrouser955/discord-player-youtubei#18]
here is the log `<ref *2> ExtractorExecutionContext {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  requiredEvents: [ 'error' ],
  player: <ref *1> Player {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    requiredEvents: [ 'error' ],
    id: '1268266853470310400',
    nodes: GuildNodeManager {
      player: [Circular *1],
      cache: Collection(0) [Map] {}
    },
    voiceUtils: VoiceUtils { player: [Circular *1], cache: Collection(0) [Map] {} },
    extractors: [Circular *2],
    events: PlayerEventsEmitter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      requiredEvents: [Array],
      [Symbol(kCapture)]: false
    },
    routePlanner: null,
    version: '6.7.0',
    lyrics: LrcLib {
      player: [Circular *1],
      api: 'https://lrclib.net/api',
      timeout: 15000,
      bucket: [SequentialBucket]
    },
    client: Client {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: 11,
      options: [Object],
      rest: [REST],
      ws: [WebSocketManager],
      actions: [ActionsManager],
      voice: [ClientVoiceManager],
      shard: null,
      users: UserManager {},
      guilds: GuildManager {},
      channels: ChannelManager {},
      sweepers: [Sweepers],
      presence: [ClientPresence],
      user: null,
      application: null,
      readyTimestamp: null,
      [Symbol(kCapture)]: true
    },
    options: {
      lockVoiceStateHandler: false,
      blockExtractors: [],
      blockStreamFrom: [],
      connectionTimeout: 20000,
      lagMonitor: 30000,
      queryCache: [QueryCache],
      useLegacyFFmpeg: false,
      skipFFmpeg: true,
      probeTimeout: 5000,
      ytdlOptions: [Object]
    },
    [Symbol(kCapture)]: false
  },
  store: Collection(0) [Map] {},
  [Symbol(kCapture)]: false
} _YoutubeiExtractor {
  context: <ref *1> ExtractorExecutionContext {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    requiredEvents: [ 'error' ],
    player: Player {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      requiredEvents: [Array],
      id: '1268266853470310400',
      nodes: [GuildNodeManager],
      voiceUtils: [VoiceUtils],
      extractors: [Circular *1],
      events: [PlayerEventsEmitter],
      routePlanner: null,
      version: '6.7.0',
      lyrics: [LrcLib],
      client: [Client],
      options: [Object],
      [Symbol(kCapture)]: false
    },
    store: Collection(0) [Map] {},
    [Symbol(kCapture)]: false
  },
  options: { name: 'youtube' },
  priority: 2,
  protocols: [ 'ytsearch', 'youtube' ],
  createBridgeQuery: [Function: createBridgeQuery],
  innerTube: undefined,
  _stream: undefined,
  rotatorOnEachReq: false
} PlayerError: Failed to extract n-token decipher algorithm
    at Player.extractNSigSourceCode (X:\dbotnew\node_modules\youtubei.js\bundle\node.cjs:17843:13)
    at Player.<anonymous> (X:\dbotnew\node_modules\youtubei.js\bundle\node.cjs:17720:28)
    at Generator.next (<anonymous>)
    at fulfilled (X:\dbotnew\node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:9196) [UnhandledEventsWarning] Warning: No event listener found for event "error". Events "error" must have event listeners.`
i have no idea what to do is it cuz of me my code discord-player discord-player-youtubei or youtube

**Comment by retrouser955** [comment]
Duplicate #15

**Comment by retrouser955** [comment]
Also, this is because of youtube constantly changing their player data which is why a lot of the scrapers like ytdl are breaking.
