### ISSUE TITLE
[cause]: SocketError: other side closed

### ISSUE THREAD

**Issue by EbookTechPL** [retrouser955/discord-player-youtubei#25]
TypeError: terminated
    at Fetch.onAborted (…/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:1939:49)
    at Fetch.emit (node:events:519:28)
    at Fetch.terminate (…/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:94:10)

Random songs (not all times one song).

### Versioning
discord-player: 6.7.1
node.js: 22.9

**Comment by retrouser955** [comment]
This is due to YouTube closing connection before the stream is completed. I believe I have a fix for this but it will take some time to implement.

**Comment by retrouser955** [comment]
I have published a beta. Please check if the issue still persist. `npm install discord-player-youtube@beta`

**Comment by EbookTechPL** [comment]
Thanks for the quick response! After ~3 hours of testing everything looks good. Of course I mean the beta version.

**Comment by retrouser955** [comment]
Hey @EbookTechPL great to hear! However, some in AndrozDev are still having this issue. I don't know if it's fully fixed yet.
