### ISSUE TITLE
using youtube-sr to search

### ISSUE THREAD

**Issue by zijipia** [retrouser955/discord-player-youtubei#9]
What do you think about using youtube-sr to search for music, playlists, related tracks... because youtubei couldn't find mixes playlist on youtube

**Comment by retrouser955** [comment]
I'm sure somewhere deep down there's a function for this. The reason I'm not using youtube-sr is because as mentioned in the readme, it is testing for v7 and we want to keep the the packages used as low as possible

**Comment by twlite** [comment]
youtube**i** uses Innertube client which basically does everything like youtube does, while `youtube-sr` is a basic scraper that can only do so much. It's best to use innertube for searches as well because it is more accurate and supports youtube music as well.
